SLAVE=slave
SOURCES_SLAVE=slaveProcess.c

VIEW=view
SOURCES_VIEW=view.c

APPLICATION=application
SOURCES_APPLICATION=applicationProcess.c

QUEUE=queue.o
SOURCES_QUEUE=queue.c

GCC=gcc

all: $(VIEW) $(SLAVE) $(APPLICATION) 


$(VIEW): $(SOURCES_SLAVE) $(QUEUE)
	$(GCC) $(SOURCES_VIEW) -o $(VIEW)

$(SLAVE): $(SOURCES_SLAVE) $(QUEUE)
	$(GCC) $(SOURCES_SLAVE) $(QUEUE) -o $(SLAVE)

$(APPLICATION): $(SOURCES_APPLICATION) $(QUEUE)
	$(GCC) $(SOURCES_APPLICATION) $(QUEUE) -o $(APPLICATION)

$(QUEUE): $(SOURCES_QUEUE)
	$(GCC) -c $(SOURCES_QUEUE)

clean:
	rm -rf *.o $(SLAVE) $(APPLICATION) $(VIEW)

.PHONY: all clean print debug
